apiVersion: v1
kind: Service
metadata:
  name: $CI_APP_NAME-svc
spec:
  selector:
    app: $CI_APP_NAME
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CI_APP_NAME
  annotations:
    buildUrl: $BUILD_URL
spec:
  progressDeadlineSeconds: 120
  replicas: 2
  selector:
    matchLabels:
      app: $CI_APP_NAME
  template:
    metadata:
      labels:
        app: $CI_APP_NAME
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: $CI_APP_NAME
        image: $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: $CI_APP_NAME-ingress-rule
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /(.*)
        backend:
          serviceName: $CI_APP_NAME-svc
          servicePort: 8080
